apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: logging-curator
  namespace: logging
spec:
  releaseName: logging-curator
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: elasticsearch-curator
    version: 2.1.0
  values:
    cronjob:
      # At 06:30 every day
      schedule: "30 6 * * *"

    configMaps:
      action_file_yml: |-
        ---
        actions:
          1:
            action: delete_indices
            description: "Clean up ES by deleting old indices"
            options:
              timeout_override:
              continue_if_exception: False
              disable_action: False
              ignore_empty_list: True
            filters:
            - filtertype: age
              source: name
              direction: older
              timestring: '%Y.%m.%d'
              unit: days
              unit_count: 30
              field:
              stats_result:
              epoch:
              exclude: False
      config_yml: |-
        ---
        client:
          hosts:
            - elasticsearch-master.logging
          port: 9200
          url_prefix:
          use_ssl: False
          certificate:
          client_cert:
          client_key:
          ssl_no_validate: True
          http_auth:
          timeout: 30
          master_only: False
        logging:
          loglevel: INFO
          logfile:
          logformat: default
          blacklist: ['elasticsearch', 'urllib3']