apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: logging-konfigurator
  namespace: logging
spec:
  releaseName: logging-konfigurator
  chart:
    repository: https://stakater.github.io/stakater-charts/
    name: konfigurator
    version: 0.0.20
  values:
    konfigurator:
      deployCRD: false