apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: mysql
  namespace: storage
spec:
  releaseName: mysql
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: mysql
    version: 1.6.2
  values:
    mysqlUser: testuser
    mysqlDatabase: testdb

    existingSecret: mysql-passwords

    persistence:
      enabled: true
      size: 1Gi
      storageClass: gp2